# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import modelsViews.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='../uploaded_media/index.png', upload_to=modelsViews.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
