# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0002_auto_20171119_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingmodel',
            old_name='safety',
            new_name='rating',
        ),
    ]
