# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-30 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0004_rankingmodel_ratedbyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='ingredients',
            field=models.ManyToManyField(db_index=True, related_name='ingredients', to='modelsViews.ingredientsModel'),
        ),
    ]
