# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0005_auto_20171230_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
