# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-03 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0006_auto_20180102_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingmodel',
            name='itemId',
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='ratedOnBrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratedOnBrand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='ratedOnProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratedOnProduct', to='modelsViews.ProductsModel'),
        ),
    ]
