# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0014_auto_20180106_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skintypemodel',
            name='notSuggested',
            field=models.ManyToManyField(blank=True, null=True, related_name='notSuggested', to='modelsViews.SuggestedReasonsConfig'),
        ),
        migrations.AlterField(
            model_name='skintypemodel',
            name='suggested',
            field=models.ManyToManyField(blank=True, null=True, related_name='suggested', to='modelsViews.SuggestedReasonsConfig'),
        ),
    ]
