# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-08 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsViews', '0015_auto_20180106_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='email',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='isBrand',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='webPage',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='modelsViews.ingredientsModel'),
        ),
    ]
